### ISSUE TITLE
EWU Meeting TH @ 11AM

### ISSUE THREAD

**Issue by cwade12c** [gcallant/Rock-Paper-Scissors-Multiclient-Server#3]
I will be at EWU between 11AM and 12PM on Thursday, June 9th to demo the final project and put finishing touches on the Proposal.

**Comment by gcallant** [comment]
Thank you Curran,
I will be there, although I am not sure if Kosuke will be there that early. He typically doesn't arrive before noon.

-Grant
On Thu, Jun 9, 2016 at 12:10 AM, -wade notifications@github.com wrote:
I will be at EWU between 11AM and 12PM on Thursday, June 9th to demo the final project and put finishing touches on the Proposal.
